name: Lenferink
description: Lenferink
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- rlenferink
- rlenferink-bot
members:
- rlenferink-test
repos:
  org:
    description: ' Meta configuration for Github Org'
    has_projects: true
  test:
    has_projects: true

