name: Lenferink
description: Lenferink
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- rlenferink
- rlenferink-bot
members:
- rlenferink-test
repos:
  org:
  test:
  test-repo-A:
  test-repo-b:
  pipeline-nexus-plugin:
    forks_url: https://github.com/jenkinsci/pipeline-global-lib-nexus-plugin

