name: config

on: [push]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    env:
      REPO_NAME: github.com/lenferink/org
    timeout-minutes: 60
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
    - name: Test Bazel
      run: bazel version
    - name: Setup token
      run: echo -e "$GH_TOKEN" > $GITHUB_WORKSPACE/token.gh
    - name: Verify
      run: ./hack/verify-all.sh
    - name: Deploy
      run: bazel run //admin:update -- --github-token-path $GITHUB_WORKSPACE/token.gh --confirm

#TODO: Add test 
