name: config

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    needs: [test-config, verify-all]
    if: github.ref == 'refs/heads/master' && github.event == 'push'
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
    - name: TEST
      run: |
        echo jahoe

