name: config

on: [push]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    env:
      REPO_NAME: github.com/lenferink/org
    timeout-minutes: 60
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
    - name: Setup Go environment
      run: |
        # Setup Go environment
        sudo mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        ls -l $GOPATH/src/$(dirname $REPO_NAME)
        sudo ln -svf $GITHUB_WORKSPACE $GOPATH/src/$REPO_NAME
        cd $GOPATH/src/$REPO_NAME
    - name: Setup token
      run: echo -e "$GH_TOKEN" > $GITHUB_WORKSPACE/token.gh
    - name: Test Bazel
      run: bazel version
    - name: Verify
      run: ./hack/verify-all.sh
    - name: Deploy
      run: bazel run //admin:update -- --github-token-path $GITHUB_WORKSPACE/token.gh --confirm

#TODO: Add test 
