name: PR

on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-18.04
    env:
      BAZEL_VERSION: 1.2.1
      REPO_NAME: github.com/lenferink/org
      GO_PATH: /go
    timeout-minutes: 60
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
    - name: Install packages
      run: |
        # Install Go
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo apt update
        sudo apt install golang-go
        sudo mkdir $GO_PATH
        export PATH=$GO_PATH/bin:$PATH
        # Setup Go environment
        mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
        cd $GOPATH/src/$REPO_NAME
        # Store GitHub token
        echo -e "$GH_TOKEN" > /tmp/token.gh
        # Install Bazel
        sudo apt-get update && sudo apt install -y wget g++ unzip zip
        wget https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
        chmod +x bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
        sudo ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
        bazel version
        # Setup Python 3
        sudo apt-get install -y python3
        sudo unlink /usr/bin/python
        sudo ln -s /usr/bin/python3 /usr/bin/python
    - name: Verify
      run: ./hack/verify-all.sh
      
