name: PR

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-18.04
    env:
      BAZEL_VERSION: 1.2.1
      REPO_NAME: github.com/lenferink/org
      GOPATH: /go
    timeout-minutes: 60
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.0' # The Go version to download (if necessary) and use.
    - name: GOOO
      run: |
        echo $GOPATH
    - name: Install packages
      run: |
        echo "PWD"
        pwd
        echo "LS"
        ls
        # Setup Go environment
        sudo mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        ls -l $GOPATH/src/$(dirname $REPO_NAME)
        sudo ln -svf $GITHUB_WORKSPACE $GOPATH/src/$REPO_NAME
        cd $GOPATH/src/$REPO_NAME
        # Store GitHub token
        echo -e "$GH_TOKEN" > /tmp/token.gh
        # Install Bazel
        sudo apt-get update && sudo apt install -y wget g++ unzip zip
        wget https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
        chmod +x bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
        sudo ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
        bazel version
        # Setup Python 3
        sudo apt-get install -y python3
        sudo unlink /usr/bin/python
        sudo ln -s /usr/bin/python3 /usr/bin/python
    - name: Verify
      run: ./hack/verify-all.sh
      
